"use client"
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ReduxProvider } from '../../lib/reduxProvider';
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import Header from './components/header';
import { SnackbarProvider } from "notistack";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Gobrax test",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en">
        <AppRouterCacheProvider>
          <body className={inter.className}>
            <Header />
            <SnackbarProvider maxSnack={3}>
              {children}
            </SnackbarProvider>
          </body>
        </AppRouterCacheProvider>
      </html>

    </ReduxProvider>
  );
}
